repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: python3 -m ruff check src/
        language: system
        always_run: true
        pass_filenames: false
        args: ["--fix", "--ignore", "F401"]
      - id: mypy
        name: mypy
        entry: python3 -m mypy src/ --strict-equality
        language: system
        always_run: true
        pass_filenames: false
      - id: pylint
        name: pylint
        entry: python3 -m pylint src/
        language: system
        always_run: true
        pass_filenames: false