site_name: HuGME
theme:
  name: material
  language: hu
  features:
    - toc.integrate
  logo: assets/logo.png
  favicon: images/favicon.png


site_url: https://hugme.nytud.hu/
repo_url: https://github.com/nytud/hugme

extra_css:
  - stylesheets/extra.css