name: Basic CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend:
    name: CI pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11, 3.12]

    steps:

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd backend && pip install -r requirements.txt
          pip install pylint ruff mypy

      - name: Linter
        run: cd backend && ruff check .

      - name: Static code checker
        run: |
          mypy src --strict-equality --install-types

      - name: Static code analysis
        run: |
          env PYTHONPATH="." python3 -m pylint src/

      - name: Safety analysis
        run: |
          pip install safety
          safety check -r requirements.txt

    #   - name: Running tests
    #     run: |
    #       pip install pytest pytest-cov pytest-env
    #       pytest .
